import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import styles from "./index.module.css";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
const user=useUser()
const {data} =api.posts.getAll.useQuery()


  return (
    
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {!user.isSignedIn &&  <SignInButton/>}
          {!!user.isSignedIn && <SignOutButton/>}
        
         
        </div>
        <div>
          {data?.map(post=>(
            <div>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
